version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: habits
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  api:
    build: ./backend
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/habits
      JWT_SECRET: supersecretkey
    ports:
      - "8001:8000"
    depends_on:
      - db

  bot:
    build: ./bot
    environment:
      API_BASE_URL: http://api:8000
      BOT_TOKEN: 8995248615:AAGKH9sBFvb0Vw5-8EQmleamsml_yS10p0I   # нужно задать в .env или передать
    depends_on:
      - api

volumes:
  postgres_data: